# -*- coding: utf-8 -*-
"""model_growth

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fAC2c0X--kgQ6UUFosjWAocCdpVgvVO
"""

# (a, 1 mark)
import numpy as np
import pandas as pd
import sys

def main():
    # (b, 0.5 marks)
    filename = sys.argv[1]
    rate_params = sys.argv[2:5]


    # (d, 0.5 marks)
    experiment_data = pd.read_csv(filename, header=None).values.flatten()

    # (c, 0.5 marks)
    rate_params = [sys.argv[i] for i in range(2, 5)]

    # Note: since the parameters that are read by sys.argv are strings, we have to convert them to floats using float(a_string)
    range_rate = np.arange(float(rate_params[0]), float(rate_params[1]), float(rate_params[2]))

    # Define a function that calculates mean squared error
    def squared_error(prediction, data):
        residual = prediction - data
        mse = (residual**2).mean()
        return mse

    # Try the parameters and choose the one with the smallest squared error
    mse = []
    # Note two modifications below: we are taking the N0 and the time vector from data
    N0 = experiment_data[0]
    t = np.linspace(0, 10, len(experiment_data))
    for r in range_rate:
        prediction = N0*np.exp(r*t)
        mse.append(squared_error(prediction, experiment_data))

    best_fit = range_rate[np.argmin(mse)]
    print('We predict the rate of growth of this bacterial population to be', best_fit)

# (e, 1 mark)
if __name__ == "__main__":
    main()





# a
# git add dummy_story.txt
# b
# git commit -m "Added my sentence to dummy_story.txt"
# c
# git push origin master